---
# tasks file for ansible-role-cultivator:prereqs.yml

#
# -----------------------------------------------------------------------------
# Pre-Req Tasks
# -----------------------------------------------------------------------------
# All the Pre-Req tasks
#

# Install Base OS Packages
- name: "[Cultivator - Pre-Reqs] Install Base Packages for Tower CLI"
  yum:
    name: "{{ cultivator_base_packages }}"
    state: present
    disablerepo: "rhel-server-rhscl-7-rpms"
  become: true
  tags: [packages]

# Create Cultivator VirtualEnv FilePath
- name: "[Cultivator - VirtualEnv] Create VirtualEnv Path"
  file:
    path: "{{ cultivator_virtualenv_path }}"
    state: directory
    mode: '0755'
  tags: [pip]

# Install Python pip Packages into VirtualEnv
- name: "[Cultivator - Pre-Reqs] Install PIP Packages for Tower CLI"
  pip:
    name: "{{ cultivator_pip_packages }}"
    virtualenv: "{{ cultivator_virtualenv_path }}"
  become: true
  tags: [pip]

- name: "Add another bin dir to system-wide $PATH."
  copy:
    dest: /etc/profile.d/custom-path.sh
    content: 'PATH=$PATH:{{ cultivator_virtualenv_path }}/bin:{{ cultivator_virtualenv_path }}/lib/python2.7/site-packages/'
  become: yes
